### PR TITLE
Handle empty key array

### PR DESCRIPTION
**Pull request by DylanPetrey**
Fix for issue #126 

Added the key filter to the `filterStr` if `keys.length > 0`

### CODE REVIEW

**Comment by DylanPetrey** [comment]
Hold on, I see a function called `filtersToSql`

**Comment by DylanPetrey** [comment]
Added the key filter to the `filterStr` if `keys.length > 0`

**Comment by DylanPetrey** [comment]
Force pushed on my fork to delete a commit and consolidate

**Comment by benvinegar** [comment]
@DylanPetrey Great find and fix – thank you. (I made a small addition to add some whitespace to your clause.)

**Pull request merged**
