### PR TITLE
feat: bar charts 

### PR DESCRIPTION
**Pull request by chiubaca**
Resolves: https://github.com/benvinegar/counterscale/issues/28

Notes:
Was slightly trickier than anticipated because because absolute positioning elements in a css table is much harder than with  plain divs in a css grid. Down the line I do wonder if if its worth refactoring the table component be plain divs and css grid _if_ the component gets more complex, would give a bit more css flexiblity but at the cost of  good html semantics.

Demo: https://counterscale.chiubaca.workers.dev/dashboard

### CODE REVIEW

**Comment by benvinegar** [comment]
Man that looks so much better (with some tiny style issues to be resolved). I'll poke at this sometime this week.

**Comment by benvinegar** [comment]
So I took a peek at this: I'd like to figure out how to achieve the result without adding empty table cells. Mostly for a11y; the markup should reflect the content.

I'm playing around with it now. We're also free to edit `TableCell` (these are copy/pasted components from shadcdn/ui).

**Comment by benvinegar** [comment]
I merged your PR then re-did how the colors were applied to drop the extra `<td> and instead use `linear-gradient` on the `<tr>` element.

8af3767cab53a4f2cad0ea5a8136dd1ef742b151

**Comment by benvinegar** [comment]
Also added #42

**Comment by chiubaca** [comment]
> So I took a peek at this: I'd like to figure out how to achieve the result without adding empty table cells. Mostly for a11y; the markup should reflect the content.
> 
> I'm playing around with it now. We're also free to edit `TableCell` (these are copy/pasted components from shadcdn/ui).

Aha, that was confusing me lots!

Nice,  thanks for fixing and merging🎉

**Pull request merged**
